# Generated by Django 5.0.13 on 2025-09-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_app', '0002_user_is_admin_user_is_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Mobile Development', 'Mobile Development'), ('Programming', 'Programming'), ('Data Science', 'Data Science'), ('Artificial Intelligence (AI)', 'Artificial Intelligence (AI)'), ('Cyber Security', 'Cyber Security'), ('Embedded Systems', 'Embedded Systems'), ('Engineering (General)', 'Engineering (General)'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Architecture Engineering', 'Architecture Engineering'), ('Aerospace Engineering', 'Aerospace Engineering'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Microbiology', 'Microbiology'), ('Biotechnology', 'Biotechnology'), ('Computational Biology', 'Computational Biology'), ('Computational Physics', 'Computational Physics'), ('Computational Chemistry', 'Computational Chemistry'), ('Earth Science', 'Earth Science'), ('Environmental Science', 'Environmental Science'), ('Astronomy & Space Science', 'Astronomy & Space Science'), ('Geology', 'Geology'), ('Meteorology', 'Meteorology'), ('Oceanography', 'Oceanography'), ('UI/UX Design', 'UI/UX Design'), ('Graphic Design', 'Graphic Design'), ('3D Modeling', '3D Modeling'), ('Video Editing', 'Video Editing'), ('Video Animation', 'Video Animation'), ('Literature Review', 'Literature Review'), ('Experimental Design', 'Experimental Design'), ('Data Collection', 'Data Collection'), ('Data Analysis', 'Data Analysis'), ('Scientific Writing', 'Scientific Writing'), ('Critical Thinking', 'Critical Thinking'), ('Hypothesis Testing', 'Hypothesis Testing'), ('Research Methodology', 'Research Methodology'), ('Project Management', 'Project Management'), ('Time Management', 'Time Management'), ('Leadership', 'Leadership'), ('Communication Skills', 'Communication Skills'), ('Presentation Skills', 'Presentation Skills'), ('Problem Solving', 'Problem Solving'), ('Writing', 'Writing'), ('Other', 'Other')], default='Other', max_length=255),
        ),
    ]
