# Generated by Django 5.0.13 on 2025-09-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_app', '0005_populate_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_hr',
            new_name='is_GPE',
        ),
        migrations.AddField(
            model_name='user',
            name='is_Mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_Registration',
            field=models.BooleanField(default=False),
        ),
    ]
