# Generated by Django 5.0.13 on 2025-09-14 17:33

import json
from django.db import migrations
from pathlib import Path

def populate_challenges(apps, schema_editor):
    Challenge = apps.get_model('space_app', 'Challenge')
    json_file = Path(__file__).resolve().parent.parent / 'data' / 'challenges.json'

    with open(json_file) as f:
        challenges = json.load(f)
        for challenge_data in challenges:
            Challenge.objects.create(
                title=challenge_data['title'],
                category=challenge_data['category'],
                description=challenge_data['description'],
                difficulty=challenge_data['difficulty'],
                image=challenge_data['image']
            )

class Migration(migrations.Migration):

    dependencies = [
        ('space_app', '0007_challenge_alter_team_challenge'),
    ]

    operations = [
        migrations.RunPython(populate_challenges),
    ]
