# Generated by Django 5.0.13 on 2025-09-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_app', '0008_populate_challenges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish')], default='en', max_length=50),
        ),
    ]
