# Generated by Django 5.0.13 on 2025-09-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_app', '0009_alter_user_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='repository_url',
            new_name='video_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies_used',
        ),
        migrations.RemoveField(
            model_name='project',
            name='website_url',
        ),
        migrations.AddField(
            model_name='project',
            name='other_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='powerpoint_file',
            field=models.FileField(blank=True, null=True, upload_to='powerpoints/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='resources_used',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='submission_status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete')], default='incomplete', max_length=20),
        ),
    ]
