# Generated by Django 5.0.13 on 2025-09-15 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_app', '0010_rename_repository_url_project_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(14)]),
        ),
    ]
