# Generated by Django 5.0.13 on 2025-09-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_app', '0011_alter_user_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='web',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
