# Generated by Django 5.0.13 on 2025-09-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_app', '0012_remove_user_web_alter_user_status'),
    ]

    operations = [
    ]
