# Generated by Django 5.0.7 on 2024-07-26 13:25

from django.db import migrations

def add_initial_skills(apps, schema_editor):
    Skill = apps.get_model('space_app', 'Skill')
    Skill.objects.create(name='Others')
    Skill.objects.create(name='Creative Design')

class Migration(migrations.Migration):

    dependencies = [
        ('space_app', '0013_auto_20250915_1232'),
    ]

    operations = [
        migrations.RunPython(add_initial_skills),
    ]
