# Generated by Django 5.0.13 on 2025-09-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_app', '0015_team_mentors_alter_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='other_skills',
            field=models.CharField(blank=True, help_text='List any other skills you have, separated by commas.', max_length=255),
        ),
    ]
