SKILLS = [
    ('web-development', 'Web Development'),
    ('mobile-development', 'Mobile Development'),
    ('programming', 'Programming'),
    ('data-science', 'Data Science'),
    ('ai', 'Artificial Intelligence (AI)'),
    ('cyber-security', 'Cyber Security'),
    ('embedded-systems', 'Embedded Systems'),
    ('engineering-general', 'Engineering (General)'),
    ('mechanical-engineering', 'Mechanical Engineering'),
    ('civil-engineering', 'Civil Engineering'),
    ('electrical-engineering', 'Electrical Engineering'),
    ('architecture-engineering', 'Architecture Engineering'),
    ('aerospace-engineering', 'Aerospace Engineering'),
    ('biomedical-engineering', 'Biomedical Engineering'),
    ('physics', 'Physics'),
    ('chemistry', 'Chemistry'),
    ('biology', 'Biology'),
    ('microbiology', 'Microbiology'),
    ('biotechnology', 'Biotechnology'),
    ('computational-biology', 'Computational Biology'),
    ('computational-physics', 'Computational Physics'),
    ('computational-chemistry', 'Computational Chemistry'),
    ('earth-science', 'Earth Science'),
    ('environmental-science', 'Environmental Science'),
    ('astronomy-space-science', 'Astronomy & Space Science'),
    ('geology', 'Geology'),
    ('meteorology', 'Meteorology'),
    ('oceanography', 'Oceanography'),
    ('ui-ux-design', 'UI/UX Design'),
    ('graphic-design', 'Graphic Design'),
    ('3d-modeling', '3D Modeling'),
    ('video-editing', 'Video Editing'),
    ('video-animation', 'Video Animation'),
    ('literature-review', 'Literature Review'),
    ('experimental-design', 'Experimental Design'),
    ('data-collection', 'Data Collection'),
    ('data-analysis', 'Data Analysis'),
    ('scientific-writing', 'Scientific Writing'),
    ('critical-thinking', 'Critical Thinking'),
    ('hypothesis-testing', 'Hypothesis Testing'),
    ('research-methodology', 'Research Methodology'),
    ('project-management', 'Project Management'),
    ('time-management', 'Time Management'),
    ('leadership', 'Leadership'),
    ('communication-skills', 'Communication Skills'),
    ('presentation-skills', 'Presentation Skills'),
    ('problem-solving', 'Problem Solving'),
    ('writing', 'Writing'),
    ('others', 'Others'),
]
