from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('dashboard/', views.dashboard_redirect_view, name='dashboard_redirect'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('participant_dashboard/', views.participant_dashboard, name='participant_dashboard'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('edit_user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('user/<int:user_id>/', views.user_detail, name='user_detail'),
    path('team/create/', views.create_team, name='create_team'),
    path('team/edit/<int:team_id>/', views.edit_team, name='edit_team'),
    path('team/<int:team_id>/project/create/', views.create_project, name='create_project'),
    path('project/<int:project_id>/', views.project_detail, name='project_detail'),
    path('project/edit/<int:project_id>/', views.edit_project, name='edit_project'),
    path('project/delete/<int:project_id>/', views.delete_project, name='delete_project'),
    path('contact/', views.contact, name='contact'),
    path('contact/success/', views.contact_success, name='contact_success'),
    path('about/', views.about_us, name='about_us'),
    path('privacy/', views.privacy_policy, name='privacy_policy'),
    path('rules/', views.rules, name='rules'),
    path('challenges/', views.challenges, name='challenges'),
    path('team/delete/<int:team_id>/', views.delete_team, name='delete_team'),
    path('teams/', views.teams, name='teams'),
    path('team/<int:team_id>/', views.team_detail, name='team_detail'),
    path('team/join/<int:team_id>/', views.join_team, name='join_team'),
    path('team/leave/<int:team_id>/', views.leave_team, name='leave_team'),
    path('team/invite/<int:team_id>/', views.invite_member, name='invite_member'),
    path('team/manage_requests/<int:team_id>/', views.manage_join_requests, name='manage_join_requests'),
    path('request/handle/<int:request_id>/<str:action>/', views.handle_join_request, name='handle_join_request'),
    path('team/cancel_join_request/<int:team_id>/', views.cancel_join_request, name='cancel_join_request'),

]
